name: "Setup KIE Tools build environment"
description: ""

inputs:
  working_dir:
    description: "kie-tools path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Print storage usage (before setup)"
      shell: bash
      run: |
        echo "STEP: Print storage usage (before setup)"
        cd ${{ inputs.working_dir }}
        du -sh .

    - name: "Create temp dir"
      shell: bash
      run: |
        echo "STEP: Create tmp dir"
        cd ${{ inputs.working_dir }}
        mkdir tmp

    - name: "Setup pnpm"
      uses: pnpm/action-setup@v2
      with:
        version: 8.7.0

    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 18.14.0

    - name: "Setup JDK 11"
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: "zulu"

    - name: "Set up GOLANG 1.21.1"
      uses: actions/setup-go@v3
      with:
        go-version: "1.21.1"

    - name: "Set up Maven"
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6

    - name: "Setup network timeout"
      shell: bash
      run: |
        echo "STEP: Setup network timeout"
        cd ${{ inputs.working_dir }}
        pnpm config set network-timeout 1000000

    - name: "Setup default Maven args"
      shell: bash
      run: |
        echo "STEP: Setup default Maven args"
        cd ${{ inputs.working_dir }}
        pnpm -r exec 'bash' '-c' 'mkdir .mvn'
        pnpm -r exec 'bash' '-c' 'echo -B > .mvn/maven.config'
        pnpm -r exec 'bash' '-c' 'echo -ntp >> .mvn/maven.config'
        pnpm -r exec 'bash' '-c' 'echo -Xmx2g > .mvn/jvm.config'

    - name: "Init DBUS"
      shell: bash
      run: |
        sudo service dbus start

    - name: "Install Fluxbox (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Install Fluxbox (Ubuntu only)"
        cd ${{ inputs.working_dir }}
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get -y install fluxbox > /dev/null 2>&1
        fi

    - name: "Start Xvfb (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Start Xvfb (Ubuntu only)"
        cd ${{ inputs.working_dir }}
        if [ "${{ runner.os }}" == "Linux" ]; then
            /usr/bin/Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        fi

    - name: "Start Fluxbox (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Start Fluxbox (Ubuntu only)"
        cd ${{ inputs.working_dir }}
        if [ "${{ runner.os }}" == "Linux" ]; then
            fluxbox -display :99 > /dev/null 2>&1 &
        fi

    - name: "Configure Pagefile (Windows only)"
      if: runner.os == 'Windows'
      uses: al-cheb/configure-pagefile-action@86589fd789a4de3e62ba628dda2cb10027b66d67 #v1.3
      with:
        minimum-size: 16GB
        maximum-size: 16GB
        disk-root: "C:"

    - name: "Increase inotify watches (Ubuntu only)"
      shell: bash
      run: |
        echo "STEP: Increase inotify watches (Ubuntu only)"
        cd ${{ inputs.working_dir }}
        if [ "${{ runner.os }}" == "Linux" ]; then
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
        fi

    - name: "Setup GOLANG packages (Linux)"
      shell: bash
      run: |
        echo "STEP: Setup GOLANG packages (Linux)"
        cd ${{ inputs.working_dir }}
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt update && \
          sudo apt install -y \
          build-essential \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          gir1.2-appindicator3-0.1
        fi

    - name: "Setup Google Chrome"
      shell: bash
      run: |
        wget "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: "Setup Chromedriver"
      shell: bash
      run: |
        CHROME_VERSION=$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json | jq -r .channels.Stable.version) && \
        wget -O /tmp/chromedriver-linux64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip && \
        unzip /tmp/chromedriver-linux64.zip -d /tmp
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/bin/
        chromedriver -v

    - name: "Print storage usage (after setup)"
      shell: bash
      run: |
        echo "STEP: Print storage usage (after setup)"
        cd ${{ inputs.working_dir }}
        du -sh .
