name: "CI :: Test Google Chrome"

on:
  pull_request:
    branches: ["**"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  run:
    environment: ci
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout @ GitHub default"
        uses: actions/checkout@v3

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Try google-chrome"
        if: always() && !cancelled()
        shell: bash
        run: |
          export DISPLAY=:99
          google-chrome --headless --enable-features=UnexpireFlagsM118 --allow-insecure-localhost --remote-debugging-pipe 3<input 4>output
          exit 0
