name: "CI :: Test Google Chrome"

on:
  pull_request:
    branches: ["**"]
    types: [opened, reopened, ready_for_review, synchronize]

env:
  TMPDIR: "${{ github.workspace }}/tmp"

jobs:
  run:
    environment: ci
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: "Support longpaths"
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: "Checkout @ GitHub default"
        uses: actions/checkout@v3

      - name: "Checkout @ Simulated squashed-merge if PR"
        id: checkout_pr
        uses: ./.github/actions/checkout-pr
        with:
          ref: ${{ github.base_ref }}

      - name: "Setup CI patterns"
        id: ci_patterns
        uses: ./.github/actions/setup-ci-patterns

      - name: "Setup build mode {none,full,partial}"
        id: setup_build_mode
        shell: bash
        run: |
          export CHANGED_SOURCE_PATHS=($(eval "git diff --name-only ${{ steps.checkout_pr.outputs.base_sha }} ${{ steps.checkout_pr.outputs.head_sha }} -- ${{ steps.ci_patterns.outputs.non_source_files_patterns_for_git_diff }}"))
          echo "Changed source paths:"
          echo ${#CHANGED_SOURCE_PATHS[@]}
          printf '%s\n' "${CHANGED_SOURCE_PATHS[@]}"

          export CHANGED_SOURCE_PATHS_IN_ROOT=($(printf '%s\n' "${CHANGED_SOURCE_PATHS[@]}" | grep -v -e "^packages" -e "^examples"))
          echo "Changed source paths in root:"
          echo ${#CHANGED_SOURCE_PATHS_IN_ROOT[@]}
          printf '%s\n' "${CHANGED_SOURCE_PATHS_IN_ROOT[@]}"

          if [ ${#CHANGED_SOURCE_PATHS[@]} -eq 0 ]; then
            echo 'No source files changed; `CI :: Build` (none) will run.'
            echo "mode=none" >> $GITHUB_OUTPUT
          elif [ ! ${{ github.event.pull_request }} ]; then
            echo 'Push to the `main` branch happened; `CI :: Build` (full) will run.'
            echo "mode=full" >> $GITHUB_OUTPUT
          elif [ ${#CHANGED_SOURCE_PATHS_IN_ROOT[@]} -eq 0 ]; then
            echo 'No source files changed in root; `CI :: Build` (partial) will run.'
            echo "mode=partial" >> $GITHUB_OUTPUT
          else
            echo 'Source files changed in root; `CI :: Build` (full) will run.'
            echo "mode=full" >> $GITHUB_OUTPUT
          fi

          echo "Done"

      - name: "Setup environment"
        if: steps.setup_build_mode.outputs.mode != 'none'
        uses: ./.github/actions/setup-env

      - name: "FULL → Bootstrap"
        if: steps.setup_build_mode.outputs.mode == 'full'
        env:
          PLAYWRIGHT_BASE__installDeps: "true"
        uses: ./.github/actions/bootstrap
